/**
 * Binary audio frames, decoded with the real `decodeAudioFrame` from bytes the backend's real encoder
 * wrote.
 *
 * `frameCodec.test.ts` builds its frames by hand from its own reading of the layout, and
 * `backend/src/ws/protocol.rs` tests its encoder against its own, so the two could agree with themselves
 * and not with each other. `contracts/audio-frames.json` is generated by `encode_audio_frame`, with the
 * header fields its decoder reads back and the samples that went in, and this file decodes the same bytes:
 * live and historic, mono and interleaved stereo, the extremes of a 16 bit sample, a time before the epoch,
 * the largest timestamp a `Number` holds exactly, and a frame with no samples at all.
 */

import { describe, expect, it } from 'vitest';

import { decodeAudioFrame, HEADER_BYTES, MAGIC, PROTOCOL_VERSION } from '@/lib/audio/frameCodec';
import { fixtures } from '@/test/contract';

/** Signed 16 bit full scale, the divisor the codec normalises samples by. */
const I16_SCALE = 32768;

/** The only payload format the codec understands: interleaved signed 16 bit PCM. */
const PCM_S16 = 0;

function bytesOf(hex: string): ArrayBuffer {
  const bytes = new Uint8Array(hex.length / 2);
  for (let index = 0; index < bytes.length; index += 1) {
    bytes[index] = Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16);
  }
  return bytes.buffer;
}

const frames = Object.entries(fixtures.audioFrames);

describe('audio frames from the backend encoder', () => {
  it('cover live and historic, mono and stereo, and a frame with no samples', () => {
    const headers = frames.map(([, frame]) => frame.header);
    expect(headers.some((header) => header.live)).toBe(true);
    expect(headers.some((header) => !header.live)).toBe(true);
    expect(headers.some((header) => header.channels === 2)).toBe(true);
    expect(headers.some((header) => header.sampleCount === 0)).toBe(true);
  });

  it.each(frames)('%s uses the header constants the codec expects', (_name, frame) => {
    expect(frame.header.magic).toBe(MAGIC);
    expect(frame.header.version).toBe(PROTOCOL_VERSION);
    expect(frame.header.formatCode).toBe(PCM_S16);
    expect(frame.header.flags & ~1).toBe(0);
    expect(frame.byteLength).toBe(HEADER_BYTES + frame.samples.length * 2);
    expect(bytesOf(frame.hex).byteLength).toBe(frame.byteLength);
  });

  it.each(frames)('%s decodes to the header fields and samples that were encoded', (_name, frame) => {
    const decoded = decodeAudioFrame(bytesOf(frame.hex));

    if (frame.header.sampleCount === 0) {
      // The codec drops an empty frame rather than hand the engine nothing to schedule.
      expect(decoded).toBeNull();
      return;
    }

    expect(decoded).not.toBeNull();
    expect(decoded?.timestampMs).toBe(frame.header.timestampMs);
    expect(decoded?.sampleRate).toBe(frame.header.sampleRate);
    expect(decoded?.channels).toBe(frame.header.channels);
    expect(decoded?.live).toBe(frame.header.live);
    expect(decoded?.samples.length).toBe(frame.header.sampleCount * frame.header.channels);
    expect(Array.from(decoded?.samples ?? [])).toEqual(
      frame.samples.map((sample) => Math.fround(sample / I16_SCALE)),
    );
  });
});
